<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WPExtension\\admin\\app\\WPExtenstionParentMenu' => $baseDir . '/apps/admin/app/WPExtenstionParentMenu.php',
);
